### ISSUE TITLE
Regarding installation error

### ISSUE THREAD

**Issue by chintanshrinath** [neulab/prompt2model#346]
Hi Team
I am trying to install package using given syntax  i.e.
**pip install prompt2model**

After installation, when I am trying to import 
**from prompt2model.utils import api_tools**., I am getting following error.

ImportError: cannot import name 'api_tools' from 'prompt2model.utils' (/anaconda/envs/chintan/lib/python3.10/site-packages/prompt2model/utils/__init__.py)

I am using **conda with python=3.10** version, please help.

Thanks

**Comment by viswavi** [comment]
There's a bug - will fix it asap.

**Comment by viswavi** [comment]
In the meanwhile, you can just skip this code block to use `gpt-3.5-turbo` by default.

**Comment by chintanshrinath** [comment]
Hi @viswavi 
Thanks for the response. But I am unable to run any import
![image](https://github.com/neulab/prompt2model/assets/7765864/2f2b8fc1-7af5-4577-98c6-c539ff1062d5)
Thanks

**Comment by viswavi** [comment]
Hi @chintanshrinath, the problem was that the latest PyPi release was out-of-sync with the latest notebook. We've updated our package on Pip, which should resolve all of these issues.

Can you do `pip install --upgrade prompt2model`, try the notebook again, and report back if this doesn't work? Sorry for the inconvenience.

**Comment by chintanshrinath** [comment]
Hi @viswavi 
yes it is working now.
Thank you for your prompt response and support
