### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by Techfluent-au** [neulab/prompt2model#386]
Hi all, I have only just stumbled on this amazing tool; having som issues either understanding or technical some assistance would be great 

prompt2model) PS C:\Users\npall\prompt2model> python prompt2model_demo.py
Traceback (most recent call last):
  File "C:\Users\npall\prompt2model\prompt2model_demo.py", line 9, in <module>
    import datasets
ModuleNotFoundError: No module named 'datasets'

**Comment by viswavi** [comment]
Did you install the `prompt2model` package first? if you do this, it will automatically install `datasets`. You can do this either via `pip install prompt2model` or by installing from source (see [README](https://github.com/neulab/prompt2model/blob/main/README.md) for detailed instructions). After installing the `prompt2model` package, you can then run the demo script.

One note: it looks like you're using Windows. We developed and tested our software on Linux rather than Windows - I believe it should also work on Windows, but you may run into unexpected issues on Windows. If this happens to you, please file an issue on Github.
